### ISSUE TITLE
感恩~ 找了很久返回墙的听网易云

### ISSUE THREAD

**Issue by Jeffery-Zhou** [jsososo/NeteaseMusic#10]
在海外，还是想听百度云，app store还有Spotify，歌曲都不全。写code没有音乐会变得非常难熬，ps 个人想写一个mac下的app爬虫掉你的接口可以么。。。。。

**Comment by jsososo** [comment]
昂～日常使用的调用量不过分的都可以的哈，高频的本身也会被自动ban掉的

**Comment by Jeffery-Zhou** [comment]
> 昂～日常使用的调用量不过分的都可以的哈，高频的本身也会被自动ban掉的

谢谢:)
