### ISSUE TITLE
bug：浏览器兼容性

### ISSUE THREAD

**Issue by he-sb** [jsososo/NeteaseMusic#11]
Firefox 74 无法自动播放点击的歌曲，包括当前歌曲播放完后自动切换的下一首歌曲，必须手动点击两次播放按钮才可以播放，可稳定复现，而同时切换至 Chrome 80 无任何问题。

**Comment by jsososo** [comment]
嗯，初步猜测可能是和音频跨域有关，因为咪咕（走了我自己服务器代理）其实没有这个问题，不过这个也好修复，主动调一下 dom的play 就可以了，我明天看看，另外发现firefox的键盘监听也是失效的哈哈

**Comment by he-sb** [comment]
感谢大佬，Firefox太草了，国内这些直播b站之类的在线播放都巨卡，还得整个Chrome备用。。

**Comment by jsososo** [comment]
修复了哈～

**Comment by he-sb** [comment]
感谢大佬，终于有地方稳定听歌了 🤣
