### ISSUE TITLE
请问为什么无法播放下架音乐呢

### ISSUE THREAD

**Issue by wzdc** [jsososo/NeteaseMusic#15]
你开头那个大标题说可以下载VIP、下架音乐 的呀 为什么我只能下载VIP音乐下载不了绝版的音乐呀？

**Comment by jsososo** [comment]
是这样的，其实他的原理也只是拿着 歌名 + 专辑 + 歌手 等信息去qq音乐搜索，选取匹配到的第一首歌，所以无法下载可能是qq音乐也没有，或者他的歌曲在qq音乐也是收费才能收听的

**Comment by wzdc** [comment]
咪咕音乐好像可以解析到听无版权音乐

**Comment by jsososo** [comment]
是哪一首歌，我看看

**Comment by wzdc** [comment]
http://music.migu.cn/v3/search?page=1&type=song&keyword=%E6%88%91%E4%BB%AC&f=html&s=1586608264&v=3.4.3&c=001002A&i=be2a2d9c648994a3e1d51825bf1c1d5f316c37d9
这个是咪咕的搜索页面 第四首就是灰色的无版权音乐
http://music.jsososo.com/apiM/search?type=song&pageno=1&keyword=%E6%88%91%E4%BB%AC&_t=1586608145508
这个是你站点的API 也是 第四首是无版权音乐
`,{"name":"我们(歌手2019)","id":"1115080468","cid":"6990539Z219","mvId":"","url":"

>http://tyst.migu.cn/public%2Fproduct5th%2Fproduct28%2F2019%2F01%2F18%2F2019%E5%B9%B401%E6%9C%8818%E6%97%A515%E7%82%B923%E5%88%86%E7%B4%A7%E6%80%A5%E5%86%85%E5%AE%B9%E5%87%86%E5%85%A5%E5%92%AA%E5%92%95%E9%9F%B3%E4%B9%90%E8%87%AA%E6%9C%89%E7%89%88%E6%9D%83427%E9%A6%96%2F%E5%85%A8%E6%9B%B2%E8%AF%95%E5%90%AC%2FMp3_64_22_16%2F6990539Z219.mp3

","album":{"picUrl":"http://mcontent.10086.cn/newlv2/new/album/20200214/1115079738/s_kc7QAwyimKitLBKN.jpg","name":"歌手第三季第二期","id":"1115079738"}`
大概就这行吧 这个解析播放不了我不知道为什么 在搜索的时候就可以解析播放
音频链接是：http://tyst.migu.cn/public%2Fproduct5th%2Fproduct28%2F2019%2F01%2F18%2F2019%E5%B9%B401%E6%9C%8818%E6%97%A515%E7%82%B923%E5%88%86%E7%B4%A7%E6%80%A5%E5%86%85%E5%AE%B9%E5%87%86%E5%85%A5%E5%92%AA%E5%92%95%E9%9F%B3%E4%B9%90%E8%87%AA%E6%9C%89%E7%89%88%E6%9D%83427%E9%A6%96%2F%E5%85%A8%E6%9B%B2%E8%AF%95%E5%90%AC%2FMp3_64_22_16%2F6990539Z219.mp3
你API的咪咕解析链http://music.jsososo.com/apiM/song/url?id=1115080468&cid=6990539Z219&_t=1586608288354

**Comment by wzdc** [comment]
歌名：我们(歌手2019)
歌手：吴青峰
在咪咕搜索页面搜我们 第四首就是

**Comment by jsososo** [comment]
emmm，我试了一下，其实网易云和qq都是可以的，咪咕确实有点问题，我明天抽空看看

**Comment by wzdc** [comment]
厉害，咪咕无版权音乐都可以解析

**Comment by jsososo** [comment]
我发现咪咕已经彻底搜不到这首歌了。。。

**Comment by wzdc** [comment]
没事 我又找到了一首歌
歌名 大眠
倒数第二个是无版权音乐

`{"name":"大眠（Live）","id":"1130145079","cid":"69704400003","mvId":"","url":"http://tyst.migu.cn/public%2Fproduct8th%2Fproduct38%2F2020%2F02%2F2715%2F2020%E5%B9%B402%E6%9C%8825%E6%97%A5%E7%8B%AC%E7%AB%8B%E9%9F%B3%E4%B9%90%E4%BA%BA%E5%BC%95%E5%85%A5%E5%A7%9C%E9%9B%86%E9%B9%8F%E5%86%85%E5%AE%B9%E5%87%86%E5%85%A51%E9%A6%96%2F%E5%85%A8%E6%9B%B2%E8%AF%95%E5%90%AC%2FMp3_64_22_16%2F69704400003.mp3","album":{"picUrl":"http://mcontent.10086.cn/newlv2/new/artist/20200203/1121442399/s_l8uSEUeciteJa4X4.jpg","name":"","id":""},"artists":[{"id":"1121442399","name":"姜集鹏"}]}`

**Comment by wzdc** [comment]
弄错了 
你去APP里面搜大眠可以搜到那个无版权的音乐 倒数第二个和倒数第一个都是没版权的

**Comment by jsososo** [comment]
看了下应该是咪咕那边版本控制的问题，这首歌已经下架了，所以通过 url 的接口已经搜不到了，但是搜索接口依然还是有返回

**Comment by wzdc** [comment]
咪咕的网页版搜索好像是不显示无版权的音乐的
找无版权音乐难

**Comment by jsososo** [comment]
我刚修复了一点无法播放点问题，现在咪咕搜索得到的应该都是能播放的

**Comment by wzdc** [comment]
我去抓了下咪咕搜索的数据 是有链接传入的，但是不能直接访问 我就先不管怎么请求才可以搜索到音乐了
然后每个歌曲url链接都有,例如这个没有版权的音乐链接ftp://218.200.160.122/public/product8th/product38/2020/02/0319/2020%E5%B9%B402%E6%9C%8803%E6%97%A518%E7%82%B940%E5%88%86%E5%86%85%E5%AE%B9%E5%87%86%E5%85%A5%E5%8D%8E%E5%A4%8F%E5%8A%A8%E5%A3%B01%E9%A6%96/%E6%A0%87%E6%B8%85%E9%AB%98%E6%B8%85/MP3_128_16_Stero/63254103501.mp3
但是要登录，我又想了想 看了看播放链接都一样就是域名不一样而已
然后换了下域名
http://tyst.migu.cn/public%2Fproduct8th%2Fproduct38%2F2020%2F01%2F0610%2F2020%E5%B9%B401%E6%9C%8803%E6%97%A516%E7%82%B947%E5%88%86%E5%86%85%E5%AE%B9%E5%87%86%E5%85%A5%E7%BA%AF%E7%B2%B9%E5%9B%BD%E9%99%85421%E9%A6%96%2F%E5%85%A8%E6%9B%B2%E8%AF%95%E5%90%AC%2FMp3_64_22_16%2F69916801388.mp3
直接可以听到咪咕没有版权的音乐

**Comment by wzdc** [comment]
域名弄错了 因为我刚刚访问的域名链接比较多 混乱了
这个才是没有版权的音乐链http://tyst.migu.cn/public/product8th/product38/2020/02/0319/2020%E5%B9%B402%E6%9C%8803%E6%97%A518%E7%82%B940%E5%88%86%E5%86%85%E5%AE%B9%E5%87%86%E5%85%A5%E5%8D%8E%E5%A4%8F%E5%8A%A8%E5%A3%B01%E9%A6%96/%E6%A0%87%E6%B8%85%E9%AB%98%E6%B8%85/MP3_128_16_Stero/63254103501.mp3

**Comment by wzdc** [comment]
我不知道你们的搜索内容为什么会过滤掉付费专辑和无版权音乐

**Comment by xsbb666** [comment]
要不 你去破解一下他那个搜索？
URL：http://jadeite.migu.cn/music_search/v2/search/searchAll?sid=a4a40888154e4a539ce7352aa70e4769b5c3270ff0ec40e487a441f63df164ac&isCorrect=1&isCopyright=1&searchSwitch=%7B%22song%22%3A1%2C%22album%22%3A0%2C%22singer%22%3A0%2C%22tagSong%22%3A1%2C%22mvSong%22%3A0%2C%22bestShow%22%3A1%2C%22songlist%22%3A0%2C%22lyricSong%22%3A0%7D&pageSize=20&text=%E5%A4%A7%E7%9C%A0&pageNo=1&feature=1011000000&sort=0

Request Head:

GET /music_search/v2/search/searchAll?sid=a4a40888154e4a539ce7352aa70e4769b5c3270ff0ec40e487a441f63df164ac&isCorrect=1&isCopyright=1&searchSwitch=%7B%22song%22%3A1%2C%22album%22%3A0%2C%22singer%22%3A0%2C%22tagSong%22%3A1%2C%22mvSong%22%3A0%2C%22bestShow%22%3A1%2C%22songlist%22%3A0%2C%22lyricSong%22%3A0%7D&pageSize=20&text=%E5%A4%A7%E7%9C%A0&pageNo=1&feature=1011000000&sort=0 HTTP/1.1
deviceId: 372b5c6d7ad32d81
sign: 02a42455a62dbfe60135cc0bb6fdc64a
mgm-Network-type: 04
IMSI: 460021131385289
HWID: 
mac: c8:f2:30:63:3d:17
timestamp: 1586676229325
appId: yyapp2
mgm-Network-standard: 01
os: android 5.1
IMEI: 861443037018199
platform: OPPO R9tm
mode: android
brand: OPPO
OAID: 
ua: Android_migu
version: 6.9.7
osVersion: android 5.1
ip: 192.168.2.101
uiVersion: A_music_3.0.1
uid: 15766697637260619197286
msisdn: MTUyMjA1NTYyNzM=
channel: 01478AT
android_id: 372b5c6d7ad32d81
Host: jadeite.migu.cn:7090
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/3.9.1

**Comment by jsososo** [comment]
我没太懂什么意思，我这边搜索用的接口都是migu的移动网页版的，它里面直接返回了可用的播放链接信息

**Comment by wzdc** [comment]
http://jadeite.migu.cn:7090
这个是移动版后台，破解到的话咪咕什么歌都可以听了

**Comment by wzdc** [comment]
http://jadeite.migu.cn:7090/music_search/v2/search/searchAll
这个是搜索的

**Comment by jsososo** [comment]
看了一下确实可以，移动app 里的接口返回的信息确实更全，会考虑一下，不过最近在忙别的改造，要晚一点再弄

**Comment by xsbb666** [comment]
我成功了 我请求咪咕音乐的app的API成功 了 具体调用方法就是只要你的cookie是像下面的格式就可以成功
`
deviceId: 372b5c6d7ad32d81
sign: 9e62112c6f875b617b6a4b96f91d419b
mgm-Network-type: 04
IMSI: 手机IMSI
HWID: 
mac: 你手机的MAC地址
timestamp: 1586685691925
appId: yyapp2
mgm-Network-standard: 01
os: android 5.1
IMEI: 手机IMEI
platform: OPPO R9tm
mode: android
brand: 手机型号
OAID: 
ua: Android_migu
version: 6.9.7
osVersion: android 5.1
ip: 192.168.2.101
uiVersion: A_music_3.0.1
uid: 账号ID
msisdn: MTUyMjA1NTYyNzM=
channel: 01478AT
android_id: 372b5c6d7ad32d81
`

我去尝试了一下 遇到了三个问题 
参数错误   ： 一般就是cookie错了
405             :  这个我真不知道是为什么 
服务器异常：GET数据错误

**Comment by xsbb666** [comment]
获取播放地址很简单
获取url参数
然后将地址ftp://218.200.160.122
改成http://tyst.migu.cn

不过我不知道行不行 可能酷我某个参数是Token令牌或其他短暂的像Token令牌一样的参数

**Comment by xsbb666** [comment]
deviceId: 372b5c6d7ad32d81 
sign: 9e62112c6f875b617b6a4b96f91d419b 
mgm-Network-type: 04 
IMSI: 手机IMSI 
HWID: 
mac: 你手机的MAC地址 
timestamp: 1586685691925 
appId: yyapp2 mgm-Network-standard: 01 os: android 5.1 
IMEI: 手机IMEI platform: OPPO R9tm mode: android 
brand: 手机型号 
OAID: ua: Android_migu version: 6.9.7 osVersion: android 5.1 
ip: 192.168.2.101 uiVersion: A_music_3.0.1 
uid: 账号ID 
msisdn: MTUyMjA1NTYyNzM= 
channel: 01478AT 
android_id: 372b5c6d7ad32d81


刚刚那个cookie没有分行 我现在分下行 数据可自行修改的

**Comment by wzdc** [comment]
请求的URL
http://jadeite.migu.cn/music_search/v2/search/searchAll?sid=5faf20e8bc414d6cb85245a27a05760804df38a2d7534aa68853d0503136921a&isCorrect=1&isCopyright=1&searchSwitch=%7B%22song%22%3A1%2C%22album%22%3A0%2C%22singer%22%3A0%2C%22tagSong%22%3A1%2C%22mvSong%22%3A0%2C%22bestShow%22%3A1%2C%22songlist%22%3A0%2C%22lyricSong%22%3A0%7D&pageSize=20&text=%E5%91%A8%E6%9D%B0%E4%BC%A6&pageNo=1&feature=1011000000&sort=0
