### ISSUE TITLE
为什么获取播放链接是另一个版本的

### ISSUE THREAD

**Issue by wzdc** [jsososo/NeteaseMusic#16]
就是这个id：000OjsEW0QrPAd
http://music.jsososo.com/apiQ/song/url?id=000OjsEW0QrPAd&type=320
去解析播放与原来的版本不一样
https://y.qq.com/n/yqq/song/000OjsEW0QrPAd.html
这是为什么呀，不止这首歌 ，有小量歌曲会出现解析其他版本问题

**Comment by jsososo** [comment]
这个接口还依赖一个参数 `mediaId`，对应其他接口里返回的 `strMediaId`，如果不传，默认 `strMediaId = mediaId` 完整的请求应该是 http://music.jsososo.com/apiQ/song/url?id=000OjsEW0QrPAd&type=320&mediaId=000Umkct2IjBZg

**Comment by wzdc** [comment]
那么麻烦呀 为什么要依赖这个呀

**Comment by jsososo** [comment]
这个对应的是媒体文件id，用来组成播放链接用的

**Comment by wzdc** [comment]
那该怎么请求mediaId

**Comment by jsososo** [comment]
基本上所有能拿到 `songmid` 的接口都能拿到 `strMediaId` 吧

**Comment by wzdc** [comment]
那你是怎么拿mediaId的呀

**Comment by jsososo** [comment]
就是从类似这种接口里获取啊，这个里面就是 `media_mid` 字段 https://api.qq.jsososo.com/search?key=%E5%91%A8%E6%9D%B0%E4%BC%A6
