### ISSUE TITLE
如果增加无损下载及歌单下载就完美了

### ISSUE THREAD

**Issue by Tzeyuen** [jsososo/NeteaseMusic#2]

**Comment by jsososo** [comment]
歌单下载有空可以考虑一下，无损的话直接从网易云接口里弄不太到，还没想到什么好办法

**Comment by jsososo** [comment]
企鹅的无损接口方面ok了，有空了把前端功能加上

**Comment by Tzeyuen** [comment]
> 企鹅的无损接口方面ok了，有空了把前端功能加上

前几天收到了Github提示你回复的邮件，非常感谢作者回复，刚刚才来试了一下。无损接口好像还是有问题，下载下来的格式是M4A和MP3。
我说说我现在的情况吧，目前非常想摆脱这类音乐软件，但是网易云上面几千首歌曲下载不下载，版权分散，有会员收费的，一次性付款的，让人非常烦，这两天刚在家里弄好的NAS，准备着手把歌曲下载下来。不然这歌曲每次消失一大堆，难受。所以找了很久都没有找到可以批量下载无损的。

**Comment by jsososo** [comment]
现在可以啦，不过无损只有企鹅的有，下载默认为无损 => 320k => 128，可以去设置里更改优先下载码率，歌单下载的在歌单里面也都有了～
