### ISSUE TITLE
用网易云的歌单，很多都是黑的

### ISSUE THREAD

**Issue by henta** [jsososo/NeteaseMusic#34]
以后考不考虑将这些黑的歌自动转换成qq音乐的链接播放呢？

**Comment by jsososo** [comment]
原来是有这个功能的，前两天搜索接口出问题了，下线了

**Comment by henta** [comment]
> 原来是有这个功能的，前两天搜索接口出问题了，下线了

好吧，这个还有机会修好吗？

**Comment by jsososo** [comment]
vip 替换的已修复
