### ISSUE TITLE
一个歌曲短时间内下载会下载到重复的歌曲，名字的对的，内容和文件大小是上一个重复的

### ISSUE THREAD

**Issue by peasshoter** [jsososo/NeteaseMusic#36]
http://y.jsososo.com/#/album?mid=003SBlkX25w4of&from=qq
我想下载的是这个，重新下载1，2次才能下载到正确的文件

**Comment by jsososo** [comment]
周末加了一个缓存策略，对获取下载链接这个接口产生了一些影响，现已修复
