### ISSUE TITLE
[特性增强] chrome 媒体播放控件 

### ISSUE THREAD

**Issue by uniquepengpeng** [jsososo/NeteaseMusic#40]
你好,  
         如下图,chrome 自带的媒体播放控件(chrome v85,需要flag开启), 请考虑支持暂停,上一首,下一首,封面等.
图中两个都是网页播放.  开启tab较多,不用进入网页控制.
![image](https://user-images.githubusercontent.com/3061047/91538083-d560d980-e949-11ea-98ba-fa4561f7007a.png)

**Comment by jsososo** [comment]
我尝试一下吧，一直不知道这个还能改的

2020年8月28日 下午4:20，pengpeng <notifications@github.com<mailto:notifications@github.com>> 写道：



你好,
如下图,chrome 自带的媒体播放控件(chrome v85,需要flag开启), 请考虑支持暂停,上一首,下一首,封面等.
图中两个都是网页播放. 开启tab较多,不用进入网页控制.
[image]<https://user-images.githubusercontent.com/3061047/91538083-d560d980-e949-11ea-98ba-fa4561f7007a.png>

**Comment by jsososo** [comment]
已支持
