### ISSUE TITLE
请问`随便听听歌`功能是否支持进入网站就自动播放

### ISSUE THREAD

**Issue by luchaoqi** [jsososo/NeteaseMusic#47]
就是这个网址: `http://music.jsososo.com/#/`
能否支持打开网址就自动播放歌曲呢? 就是跟youtube一样点开就能自动播放不需要再按一下播放键
是因为我ip问题么? 我发现我打开网站后跳过了好多歌曲以后得再次点击播放键才能播放

**Comment by he-sb** [comment]
盲猜一个 Firefox 受害者？🙈

**Comment by jsososo** [comment]
自动播放有一个问题，因为这个网站和youtube不同的是，他没有首页的概念，一进来就能播放，但可能会出现歌曲信息没加载玩或者歌曲信息加载了，歌曲链接没加载出来等情况
