### ISSUE TITLE
音乐下载类型

### ISSUE THREAD

**Issue by godmanbely** [jsososo/NeteaseMusic#6]
这个QQ音乐下载不是MP3格式嘛？

**Comment by jsososo** [comment]
是的，qq音乐下载的和现在他们官网在线播放的都是m4a格式的，mp3的和无损的链接我有空了再试试获取方法

**Comment by godmanbely** [comment]
建议加入咪咕音乐的API，咪咕音乐里面也有不少免费听的收费歌曲。感谢

**Comment by jsososo** [comment]
嗯，有这个想法，本地都已经建了一个咪咕api的项目了，不过还没开始写。

**Comment by godmanbely** [comment]
谢谢提供方便的听歌平台

**Comment by jsososo** [comment]
企鹅的无损和mp3接口方面ok了，有空了把前端功能加上

**Comment by jsososo** [comment]
ok，现在企鹅的无损和mp3都可以了，优先下载格式可以去设置页自己设置哈，咪咕的初始接口也ok了，也放到github上了，不过接入这个网页感觉还要一会儿时间
